ekf_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    publish_tf: true
    publish_acceleration: true
    print_diagnostics: true
    debug: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /wheel_odom
    odom0_config: [
      true, true, false,   # x, y, z (pose)
      false, false, true,   # roll, pitch, yaw (pose)
      true,  true,  false,   # vx, vy, vz (twist)
      false, false, true,   # vroll, vpitch, vyaw (twist)
      false, false, false    # ax, ay, az (accel)
    ]
    odom0_differential: false
    odom0_relative: false
    odom0_nodelay: true
    odom0_queue_size: 20