ekf_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    publish_tf: true
    publish_acceleration: true
    print_diagnostics: true
    debug: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # --- Wheel Odometry (twist-only) ---
    odom0: /wheel_odom
    odom0_config: [
      false, false, false,   # x, y, z (pose)
      false, false, false,   # roll, pitch, yaw (pose)
      true,  true,  false,   # vx, vy, vz (twist)
      false, false, false,   # vroll, vpitch, vyaw (twist)
      false, false, false    # ax, ay, az (accel)
    ]
    odom0_differential: false
    odom0_relative: false
    odom0_nodelay: true
    odom0_queue_size: 5

    # # --- IMU (yaw + yaw rate) ---
    # imu0: /imu
    # imu0_config: [
    #   false, false, false,   # x, y, z (pose)
    #   false, false, true,    # roll, pitch, yaw (pose)  <-- fuse yaw from IMU
    #   false, false, false,   # vx, vy, vz
    #   false, false, true     # vroll, vpitch, vyaw
    # ]
    # imu0_differential: false
    # imu0_relative: false
    # imu0_nodelay: true
    # imu0_queue_size: 5
    # imu0_remove_gravitational_acceleration: true

    imu0: /imu/data
    imu0_config: [ false, false, false,    # x y z
                   false, false, false,    # roll pitch yaw
                   false, false, false,    # vx vy vz
                   false, false, true,     # vroll vpitch vyaw (yaw rate)
                   false, false, false ]   # ax ay az OFF for now
    imu0_relative: true
    imu0_differential: false
    imu0_queue_size: 20
    imu0_remove_gravitational_acceleration: false
    print_diagnostics: true